let rows=[],specials=[],ferie=[],result=[];
const $=x=>document.getElementById(x);
$("file").onchange=async e=>{let f=e.target.files[0];if(!f)return;let b=await f.arrayBuffer();let w=XLSX.read(b,{type:"array",cellDates:true});rows=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{header:1,defval:""});$("info").textContent="Caricato: "+f.name;$("run").disabled=false};
function tag(container,text,fn){let x=document.createElement("span");x.className="tag";x.textContent=text;let b=document.createElement("button");b.textContent="×";b.onclick=()=>{fn();x.remove()};x.appendChild(b);$(container).appendChild(x)}
$("addSp").onclick=()=>{let p=$("spPerson").value,d=$("spDate").value,q=$("spReq").value;if(!d||!q)return;specials.push({p,d,q});tag("spList",p+" · "+d+" · "+q,()=>specials=specials.filter(x=>!(x.p==p&&x.d==d&&x.q==q)))};
$("addFerie").onclick=()=>{let d=$("ferie").value;if(!d||ferie.includes(d))return;ferie.push(d);tag("ferieList",d,()=>ferie=ferie.filter(x=>x!=d))};
function D(v){if(v instanceof Date)return new Date(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v=="number"){let x=XLSX.SSF.parse_date_code(v);return new Date(x.y,x.m-1,x.d)}let x=new Date(v);return isNaN(x)?null:new Date(x.getFullYear(),x.getMonth(),x.getDate())}
const iso=d=>d.toISOString().slice(0,10),fmt=d=>d.toLocaleDateString("it-IT");
function isCam(v){let s=String(v??"").trim().toLowerCase();return s=="camacho"||/(^|[\/\s(])cam(?:acho)?($|[\/\s(])/.test(s)}
function L(row,d){let m=[];row.forEach((v,i)=>{if(isCam(v))m.push(i)});if(!m.length)return"";if(m.some(i=>i==14||i==15))return"assenza";if(m.includes(1)&&m.includes(2))return"Guardia San Vito";if(m.includes(1))return"mattina San Vito";if(m.includes(2))return"pomeriggio San Vito";if(m.includes(4)){let s=String(row[4]).toLowerCase();if(s.includes("(n)"))return"notte PN";if(s.includes("(end)"))return"mattina PN";if(s.includes("(d)"))return"guardia diurna PN"}if(m.includes(5))return"8-15.30 spilimbergo";if(m.some(i=>[6,7,8].includes(i)))return"mattina San Vito";if(m.includes(10))return d.getDay()==1?"mattina San Vito":d.getDay()==4?"pomeriggio San Vito":"";return""}
function C(d){let n=Math.round((d-new Date(2026,8,1))/864e5),cycle=Math.floor(n/4),pos=((n%4)+4)%4,team=((3+cycle-1)%8)+1;if(team==5)return"";return["GIORNO","NOTTE","SMONTO NOTTE",""][pos]}
function need(d,l,c){let w=d.getDay()==0||d.getDay()==6,sv=l.includes("San Vito"),pn=["guardia diurna PN","mattina PN"].includes(l),sp=l.includes("spilimbergo"),g=["Guardia San Vito","guardia diurna PN"].includes(l);if(g&&c=="NOTTE")return"19.15";if(l=="notte PN"&&c=="GIORNO")return"18.45";if(l=="Smonto notte"&&c=="GIORNO")return"7.15";if(sv&&c=="SMONTO NOTTE")return"7.15";if((pn||sp)&&c=="SMONTO NOTTE")return"7.00";if(w&&(sv||pn)&&c=="GIORNO")return"7.15 e tutto il giorno";if(sv&&c=="GIORNO")return"7.30";if((pn||sp)&&c=="GIORNO")return"7.15";return""}
$("run").onclick=()=>{let a=[];for(let r of rows){let d=D(r[0]);if(d)a.push({d,l:L(r,d)})}for(let i=1;i<a.length;i++)if(a[i-1].l=="notte PN")a[i].l="Smonto notte";result=a.map(x=>{let l=x.l,c=C(x.d),sd=iso(x.d),sl=specials.find(s=>s.d==sd&&s.p=="Ludovica"),sc=specials.find(s=>s.d==sd&&s.p=="Luciano");if(sl)l=sl.q;if(sc)c=sc.q;if(ferie.includes(sd))c="";return{d:x.d,l,c,n:need(x.d,l,c)}});for(let i=0;i<result.length-1;i++)if(ferie.includes(iso(result[i].d))&&C(result[i].d)=="NOTTE"&&!specials.some(s=>s.p=="Luciano"&&s.d==iso(result[i+1].d)))result[i+1].c="";$("body").innerHTML="";result.forEach(r=>{let tr=document.createElement("tr");if([0,6].includes(r.d.getDay()))tr.className="weekend";[fmt(r.d),r.l,r.c,r.n].forEach(v=>{let td=document.createElement("td");td.textContent=v;tr.appendChild(td)});$("body").appendChild(tr)});$("out").hidden=false;$("save").disabled=false};
$("save").onclick=()=>{let a=[["Data","Ludovica","Luciano","Necessità"],...result.map(r=>[fmt(r.d),r.l,r.c,r.n])],w=XLSX.utils.aoa_to_sheet(a),b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,w,"Elaborazione");w["!cols"]=[{wch:14},{wch:24},{wch:20},{wch:28}];XLSX.writeFile(b,"elaborazione_turni.xlsx")};